### ISSUE TITLE
i18n Translation Issue

### ISSUE THREAD

**Issue by alcomposer** [drobilla/lilv#31]
<details><summary>System Info</summary>
<p>

jalv 1.6.4
lilv 0.24.6
lv2 1.16.0

OS: Arch Linux x86_64 
Host: TM1701 
Kernel: 5.4.6-arch3-1 
Uptime: 1 hour, 5 mins 
Packages: 2501 (pacman), 3 (dpkg), 21 (flatpak) 
Shell: bash 5.0.11 
Resolution: 1920x1080 
DE: GNOME 3.34.2 
WM: Mutter 
WM Theme: Adwaita 
Theme: Adwaita [GTK2/3] 
Icons: Adwaita [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i7-8550U (8) @ 4.000GHz 
GPU: NVIDIA GeForce MX150 
GPU: Intel UHD Graphics 620 
Memory: 3387MiB / 15899MiB 

</p>
</details>

### Summary:
Jalv.gtk & Ardour (LV2 host plugin GUI) both exhibit issues with i18n translations. 

Tested using https://github.com/sfztools/sfizz/commit/90bb90c398cd1855fc33b5cb1796a7e92788db85

### Issues are:

* Scalepoint text can get stuck at a different language than system setting
* Plugin Description (in Ardour) text does not translate
* Group Labels are not translated into locale language (other than default) unless the size of translated string, is small (a few characters)
* Random scalepoint behaviour- text with capitalization will translate:  
`x1 Sovracampionamento` will translate
`x1 sovracampionamento` will not translate
* Scalepoint will also get translate if string is small (a few characters)

`LANG=it_IT.UTF-8 jalv.gtk http://sfztools.github.io/sfizz`
![Italian_but_Configuration_is_English](https://user-images.githubusercontent.com/12004932/71568737-8f811680-2b19-11ea-956c-e2100ef56267.png)
`jalv.gtk http://sfztools.github.io/sfizz` (run after LANG=Italian)
![EN_but_still_Italian_scalepoints](https://user-images.githubusercontent.com/12004932/71568738-9019ad00-2b19-11ea-8381-c769005be28d.png)

**Comment by jpcima** [comment]
I posted a patch. It's maybe not programmed the best, but I believe it fixes it.
The scalepoints are not going throught the i18n routine.
https://gist.github.com/jpcima/49ce8f8168f1cbf6727be2bbad759d49

**Comment by drobilla** [comment]
Hm, yeah, that's not right.  Though there isn't any weird stuff where settings "stick" or translation depends on length, it's just effectively random which value is used when the host uses the "get_one" methods and there are several values.

I think it is safe to fix this everywhere though, not just for scale points as in the above fix, which should fix the same problem wherever the host does this (which is probably the description issue mentioned, and many others nobody has noticed yet).

So, I went with that approach in bd0d8e6, which should fix the problem.  Thanks.

**Comment by redtide** [comment]
Just updated Arch and it seems the problem is still there. The translations are Italian and French and I get the same string translated in French instead Italian (I mean it's constant, not random wrong string) and I don't see anything relevant in sfizz.ttl.
![sfizz-lv2-i18n](https://user-images.githubusercontent.com/1171962/80757612-b20d5580-8b34-11ea-86d2-6f92624d5f82.png)

**Comment by drobilla** [comment]
The French shows up for me as well (with whatever LANG, though I use `en_GB`).

This seems to be because Jalv is using lilv_world_get() for property control labels which does not use the translation selection mechanism.  I suppose it probably should as well.
